name: 'Check for IT Change ID in PR title'
description: 'Checks for IT Change ID in PR title'
inputs:
  GH_API_TOKEN:
    description: 'GitHub API Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout codebase'
      uses: actions/checkout@v4
      with:
        repository: nn-dma/link-work-item
        path: .
        fetch-depth: 0

    - name: 'Check for IT Change ID'
      run: |
        cd scripts
        echo "{{ github.head_ref }}: ${{ github.head_ref }}"
        echo "{{ inputs.GH_API_TOKEN }}: ${{ inputs.GH_API_TOKEN }}"
        echo "{{ github.repository }}: ${{ github.repository }}"
        ./get_pull_request_details_for_hash_github.sh ${{ github.head_ref }} ${{ inputs.GH_API_TOKEN }} ${{ github.repository }}
      shell: bash
